CREATE TABLE API_KEYS (
    ID NUMBER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER,
    KEY_VALUE VARCHAR2(64) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(100),
    IS_ACTIVE NUMBER,
    CREATED_AT TIMESTAMP,
    LAST_USED TIMESTAMP
);

CREATE TABLE DEVICES (
    DEVICE_ID VARCHAR2(20) NOT NULL,
    DESCRIPTION VARCHAR2(50)
);

CREATE TABLE LOCATION (
    ID CHAR(36) NOT NULL DEFAULT SYS_GUID() PRIMARY KEY,
    DEVICE_ID VARCHAR2(20) NOT NULL,
    TIMESTAMP_UTC_START TIMESTAMP,
    TIMESTAMP_UTC_END TIMESTAMP,
    LATITUDE NUMBER,
    LONGITUDE NUMBER,
    ALTITUDE NUMBER,
    LOCATION_GEOCODE_ID CHAR(32)
);

CREATE TABLE LOCATION_DATA (
    ID CHAR(36) NOT NULL DEFAULT SYS_GUID() PRIMARY KEY,
    DEVICE_ID VARCHAR2(20) NOT NULL,
    TIMESTAMP_UTC TIMESTAMP,
    LATITUDE NUMBER,
    LONGITUDE NUMBER,
    ALTITUDE NUMBER
);

CREATE TABLE LOCATION_GEOCODE (
    ID CHAR(32) NOT NULL PRIMARY KEY,
    PLACE_ID VARCHAR2(350),
    PLUS_CODE VARCHAR2(20),
    PLUS_CODE_SHORT VARCHAR2(50),
    FORMATTED_ADDRESS VARCHAR2(500),
    ADDRESS_LINE1 VARCHAR2(200),
    ADDRESS_LINE2 VARCHAR2(200),
    HOUSENUMBER VARCHAR2(200),
    STREET VARCHAR2(200),
    SUBURB VARCHAR2(100),
    CITY VARCHAR2(100),
    POSTCODE VARCHAR2(20),
    COUNTY VARCHAR2(100),
    STATE VARCHAR2(100),
    COUNTRY VARCHAR2(100),
    RESULT_TYPE VARCHAR2(50),
    GEOCODE_DISTANCE_M NUMBER,
    TIMEZONE_NAME VARCHAR2(50),
    TIMEZONE_OFFSET_STD VARCHAR2(10),
    TIMEZONE_OFFSET_DST VARCHAR2(10),
    GEOCODED_AT TIMESTAMP
);

CREATE TABLE LOG (
    ID CHAR(36) NOT NULL,
    DATE_TIME TIMESTAMP,
    MESSAGE VARCHAR2(2000)
);

CREATE TABLE PARAMETER (
    KEY VARCHAR2(30) NOT NULL,
    VALUE VARCHAR2(512)
);

CREATE TABLE SCHEDULER_LOG (
    ID NUMBER NOT NULL,
    JOB_NAME VARCHAR2(100),
    RUN_DATE DATE,
    ROWS_UPDATED NUMBER,
    NOTES VARCHAR2(4000)
);

CREATE TABLE SESSION_DATA (
    ID CHAR(36) NOT NULL DEFAULT SYS_GUID() PRIMARY KEY,
    DEVICE_ID VARCHAR2(20) NOT NULL,
    START_UTC TIMESTAMP,
    END_UTC TIMESTAMP,
    SESSION_TYPE CHAR(1),
    GEOCODE_START CHAR(32),
    GEOCODE_END CHAR(32)
);

CREATE TABLE USERS (
    ID NUMBER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255),           -- NULL for Google-only accounts
    EMAIL VARCHAR2(100),
    CREATED_AT TIMESTAMP,
    IS_ADMIN NUMBER,
    GOOGLE_ID VARCHAR2(255),               -- Google OAuth subject ID
    GOOGLE_AVATAR_URL VARCHAR2(500),       -- Google profile picture URL
    CONSTRAINT UQ_USERS_GOOGLE_ID UNIQUE (GOOGLE_ID)
);

CREATE TABLE USER_DEVICES (
    USER_ID NUMBER NOT NULL,
    DEVICE_ID VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_USER_DEVICES PRIMARY KEY (USER_ID, DEVICE_ID)
);


-- Foreign Keys
ALTER TABLE API_KEYS ADD CONSTRAINT FK_API_KEYS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;
ALTER TABLE USER_DEVICES ADD CONSTRAINT FK_USER_DEVICES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;
-- Note: LOCATION tables and SESSION tables are loosely coupled in this schema dump or lack explicit FKs in the JSON.
