CREATE TABLE API_KEYS (
    ID CHAR(36) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_ID CHAR(36),
    KEY_VALUE VARCHAR2(64) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(100),
    IS_ACTIVE NUMBER,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    LAST_USED TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0
);

CREATE TABLE DEVICES (
    DEVICE_ID VARCHAR2(20) NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0
);



CREATE TABLE LOCATION_DATA (
    ID CHAR(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    DEVICE_ID VARCHAR2(20) NOT NULL,
    TIMESTAMP_UTC TIMESTAMP,
    LATITUDE NUMBER,
    LONGITUDE NUMBER,
    ALTITUDE NUMBER,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0
);

CREATE TABLE LOCATION_GEOCODE (
    ID CHAR(32) NOT NULL PRIMARY KEY,
    PLACE_ID VARCHAR2(350),
    PLUS_CODE VARCHAR2(20),
    PLUS_CODE_SHORT VARCHAR2(50),
    FORMATTED_ADDRESS VARCHAR2(500),
    ADDRESS_LINE1 VARCHAR2(200),
    ADDRESS_LINE2 VARCHAR2(200),
    HOUSENUMBER VARCHAR2(200),
    STREET VARCHAR2(200),
    SUBURB VARCHAR2(100),
    CITY VARCHAR2(100),
    POSTCODE VARCHAR2(20),
    COUNTY VARCHAR2(100),
    STATE VARCHAR2(100),
    COUNTRY VARCHAR2(100),
    RESULT_TYPE VARCHAR2(50),
    GEOCODE_DISTANCE_M NUMBER,
    TIMEZONE_NAME VARCHAR2(50),
    TIMEZONE_OFFSET_STD VARCHAR2(10),
    TIMEZONE_OFFSET_DST VARCHAR2(10),
    GEOCODED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0
);

CREATE TABLE LOG (
    ID CHAR(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MESSAGE VARCHAR2(2000)
);

CREATE TABLE PARAMETER (
    KEY VARCHAR2(30) NOT NULL PRIMARY KEY,
    VALUE VARCHAR2(512),
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0
);

CREATE TABLE SCHEDULER_LOG (
    ID CHAR(36) DEFAULT SYS_GUID() PRIMARY KEY,
    JOB_NAME VARCHAR2(100),
    RUN_DATE DATE,
    ROWS_UPDATED NUMBER,
    NOTES VARCHAR2(4000)
);

CREATE TABLE SESSION_DATA (
    ID CHAR(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY,
    DEVICE_ID VARCHAR2(20) NOT NULL,
    CAR_ID CHAR(36),
    START_UTC TIMESTAMP,
    END_UTC TIMESTAMP,
    SESSION_TYPE CHAR(1),
    GEOCODE_START CHAR(32),
    GEOCODE_END CHAR(32),
    COST NUMBER,
    DISTANCE NUMBER,
    TIME_TRAVELED NUMBER,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0
);

CREATE TABLE USERS (
    ID CHAR(36) DEFAULT SYS_GUID() PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255),           -- NULL for Google-only accounts
    EMAIL VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_ADMIN NUMBER,
    GOOGLE_ID VARCHAR2(255),               -- Google OAuth subject ID
    GOOGLE_AVATAR_URL VARCHAR2(500),       -- Google profile picture URL
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0,
    CONSTRAINT UQ_USERS_GOOGLE_ID UNIQUE (GOOGLE_ID)
);

CREATE TABLE USER_DEVICES (
    USER_ID CHAR(36) NOT NULL,
    DEVICE_ID VARCHAR2(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0,
    CONSTRAINT PK_USER_DEVICES PRIMARY KEY (USER_ID, DEVICE_ID)
);


CREATE TABLE CARS (
    ID CHAR(36) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_ID CHAR(36),
    DESCRIPTION VARCHAR2(100),
    LICENSE_PLATE VARCHAR2(20),
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0
);

CREATE TABLE FUEL (
    ID CHAR(36) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_ID CHAR(36) NOT NULL,
    CAR_ID CHAR(36) NOT NULL,
    TIMESTAMP_UTC TIMESTAMP NOT NULL,
    TOTAL_VALUE NUMBER NOT NULL,
    LITERS NUMBER NOT NULL,
    TOTAL_KILOMETERS NUMBER DEFAULT 0,
    KILOMETER_PER_LITER NUMBER DEFAULT 0,
    PRICE_PER_KILOMETER NUMBER DEFAULT 0,
    RECEIPT_IMAGE BLOB,
    RECEIPT_MIME VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0
);

CREATE TABLE BLUETOOTH (
    ID CHAR(36) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_ID CHAR(36) NOT NULL,
    NAME VARCHAR2(100),
    DESCRIPTION VARCHAR2(255),
    ADDRESS VARCHAR2(100),
    CAR_ID CHAR(36),
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0
);

CREATE TABLE SYNC_STATE (
    ID VARCHAR2(50) PRIMARY KEY,
    LAST_SYNC TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP)
);

CREATE TABLE INSURANCE (
    ID CHAR(36) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_ID CHAR(36) NOT NULL,
    CAR_ID CHAR(36) NOT NULL,
    PAYMENT_DATE TIMESTAMP NOT NULL,
    PERIOD VARCHAR2(50) NOT NULL,
    AMOUNT NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0
);

CREATE TABLE MAINTENANCE (
    ID CHAR(36) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_ID CHAR(36) NOT NULL,
    CAR_ID CHAR(36) NOT NULL,
    MAINTENANCE_DATE TIMESTAMP NOT NULL,
    AMOUNT NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(1000) NOT NULL,
    RECEIPT_IMAGE BLOB,
    RECEIPT_MIME VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0
);
