-- Indexes for performance optimization

-- USERS
CREATE UNIQUE INDEX IDX_USERS_USERNAME ON USERS(USERNAME);
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);

-- API_KEYS
CREATE UNIQUE INDEX IDX_API_KEYS_VALUE ON API_KEYS(KEY_VALUE);
CREATE INDEX IDX_API_KEYS_USER_ID ON API_KEYS(USER_ID);

-- USER_DEVICES
-- Note: Primary Key (USER_ID, DEVICE_ID) automatically creates an index.
-- But we query purely by DEVICE_ID to find owner, or purely by USER_ID to find devices.
-- The PK index covers (USER_ID, ...) queries. 
-- We also have a UNIQUE constraint on DEVICE_ID (one owner per device), which enforces an index on DEVICE_ID.
-- So explicit indexes here might be redundant but safe to ensure existence for performance.
CREATE INDEX IDX_USER_DEVICES_USER_ID ON USER_DEVICES(USER_ID);

-- SESSION_DATA
CREATE INDEX IDX_SESSION_DATA_DEVICE_START ON SESSION_DATA(DEVICE_ID, START_UTC);
CREATE INDEX IDX_SESSION_DATA_START_UTC ON SESSION_DATA(START_UTC);

-- LOCATION_DATA (High volume table)
CREATE INDEX IDX_LOCATION_DATA_DEVICE_TS ON LOCATION_DATA(DEVICE_ID, TIMESTAMP_UTC);
CREATE INDEX IDX_LOCATION_DATA_TS ON LOCATION_DATA(TIMESTAMP_UTC);

-- LOCATION (Aggregated segments)
CREATE INDEX IDX_LOCATION_DEVICE_START ON LOCATION(DEVICE_ID, TIMESTAMP_UTC_START);
CREATE INDEX IDX_LOCATION_GEOCODE_FK ON LOCATION(LOCATION_GEOCODE_ID);

-- LOCATION_GEOCODE
CREATE INDEX IDX_LOC_GEOCODE_PLACE_ID ON LOCATION_GEOCODE(PLACE_ID);
CREATE INDEX IDX_LOC_GEOCODE_PLUS_CODE ON LOCATION_GEOCODE(PLUS_CODE);

-- LOG
CREATE INDEX IDX_LOG_DATE_TIME ON LOG(DATE_TIME);
