CREATE TABLE INSURANCE (
    ID CHAR(36) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_ID CHAR(36) NOT NULL,
    CAR_ID CHAR(36) NOT NULL,
    PAYMENT_DATE TIMESTAMP NOT NULL,
    PERIOD VARCHAR2(50) NOT NULL,
    AMOUNT NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0
);
