CREATE TABLE MAINTENANCE (
    ID CHAR(36) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_ID CHAR(36) NOT NULL,
    CAR_ID CHAR(36) NOT NULL,
    MAINTENANCE_DATE TIMESTAMP NOT NULL,
    AMOUNT NUMBER NOT NULL,
    DESCRIPTION VARCHAR2(1000) NOT NULL,
    RECEIPT_IMAGE BLOB,
    RECEIPT_MIME VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    IS_DELETED NUMBER DEFAULT 0
);
