-- ==============================================================================
-- MIGRATION SCRIPT: INT IDENTITY TO UUID (SYS_GUID)
-- This script migrates all incremental numeric ID columns to CHAR(36) UUIDs
-- while preserving existing data and foreign key relationships.
--
-- IMPORTANT: Run this as a single script block from your SQL client (e.g. SQL Developer)
-- or execute it line by line.
-- Ensure you have a database backup before proceeding!
-- ==============================================================================

-- 1. Disable Constraints & Drop existing foreign keys
ALTER TABLE API_KEYS DROP CONSTRAINT FK_API_KEYS_USER;
ALTER TABLE USER_DEVICES DROP CONSTRAINT FK_USER_DEVICES_USER;
ALTER TABLE CARS DROP CONSTRAINT FK_CARS_USER;
ALTER TABLE SESSION_DATA DROP CONSTRAINT FK_SESSION_CAR;
ALTER TABLE FUEL DROP CONSTRAINT FK_FUEL_USER;
ALTER TABLE FUEL DROP CONSTRAINT FK_FUEL_CAR;
ALTER TABLE BLUETOOTH DROP CONSTRAINT FK_BLUETOOTH_USER;
ALTER TABLE BLUETOOTH DROP CONSTRAINT FK_BLUETOOTH_CAR;

-- 2. Add New UUID Columns to ALL tables
-- Adding NEW_ID to tables with IDENTITY columns
ALTER TABLE USERS ADD NEW_ID CHAR(36);
ALTER TABLE CARS ADD NEW_ID CHAR(36);
ALTER TABLE FUEL ADD NEW_ID CHAR(36);
ALTER TABLE BLUETOOTH ADD NEW_ID CHAR(36);
ALTER TABLE API_KEYS ADD NEW_ID CHAR(36);

-- Adding Reference Columns
ALTER TABLE API_KEYS ADD NEW_USER_ID CHAR(36);
ALTER TABLE USER_DEVICES ADD NEW_USER_ID CHAR(36);
ALTER TABLE CARS ADD NEW_USER_ID CHAR(36);
ALTER TABLE SESSION_DATA ADD NEW_CAR_ID CHAR(36);
ALTER TABLE FUEL ADD NEW_USER_ID CHAR(36);
ALTER TABLE FUEL ADD NEW_CAR_ID CHAR(36);
ALTER TABLE BLUETOOTH ADD NEW_USER_ID CHAR(36);
ALTER TABLE BLUETOOTH ADD NEW_CAR_ID CHAR(36);

-- 3. Generate UUIDs for Primary Keys
UPDATE USERS SET NEW_ID = SYS_GUID();
UPDATE CARS SET NEW_ID = SYS_GUID();
UPDATE FUEL SET NEW_ID = SYS_GUID();
UPDATE BLUETOOTH SET NEW_ID = SYS_GUID();
UPDATE API_KEYS SET NEW_ID = SYS_GUID();

-- 4. Map the new IDs across all Foreign Key references safely
-- Map USERS
UPDATE API_KEYS a SET NEW_USER_ID = (SELECT NEW_ID FROM USERS u WHERE u.ID = a.USER_ID);
UPDATE USER_DEVICES ud SET NEW_USER_ID = (SELECT NEW_ID FROM USERS u WHERE u.ID = ud.USER_ID);
UPDATE CARS c SET NEW_USER_ID = (SELECT NEW_ID FROM USERS u WHERE u.ID = c.USER_ID);
UPDATE FUEL f SET NEW_USER_ID = (SELECT NEW_ID FROM USERS u WHERE u.ID = f.USER_ID);
UPDATE BLUETOOTH b SET NEW_USER_ID = (SELECT NEW_ID FROM USERS u WHERE u.ID = b.USER_ID);

-- Map CARS
UPDATE SESSION_DATA s SET NEW_CAR_ID = (SELECT NEW_ID FROM CARS c WHERE c.ID = s.CAR_ID);
UPDATE FUEL f SET NEW_CAR_ID = (SELECT NEW_ID FROM CARS c WHERE c.ID = f.CAR_ID);
UPDATE BLUETOOTH b SET NEW_CAR_ID = (SELECT NEW_ID FROM CARS c WHERE c.ID = b.CAR_ID);


-- 5. Drop the old original columns, rename NEW columns, and set as PK
-- NOTE: dropping IDENTITY columns requires dropping limits.

-- USERS
ALTER TABLE USERS DROP PRIMARY KEY;
ALTER TABLE USERS DROP COLUMN ID;
ALTER TABLE USERS RENAME COLUMN NEW_ID TO ID;
ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (ID);
ALTER TABLE USERS MODIFY ID DEFAULT SYS_GUID();

-- CARS
ALTER TABLE CARS DROP PRIMARY KEY;
ALTER TABLE CARS DROP COLUMN ID;
ALTER TABLE CARS DROP COLUMN USER_ID;
ALTER TABLE CARS RENAME COLUMN NEW_ID TO ID;
ALTER TABLE CARS RENAME COLUMN NEW_USER_ID TO USER_ID;
ALTER TABLE CARS ADD CONSTRAINT PK_CARS PRIMARY KEY (ID);
ALTER TABLE CARS MODIFY ID DEFAULT SYS_GUID();

-- API_KEYS
ALTER TABLE API_KEYS DROP PRIMARY KEY;
ALTER TABLE API_KEYS DROP COLUMN ID;
ALTER TABLE API_KEYS DROP COLUMN USER_ID;
ALTER TABLE API_KEYS RENAME COLUMN NEW_ID TO ID;
ALTER TABLE API_KEYS RENAME COLUMN NEW_USER_ID TO USER_ID;
ALTER TABLE API_KEYS ADD CONSTRAINT PK_API_KEYS PRIMARY KEY (ID);
ALTER TABLE API_KEYS MODIFY ID DEFAULT SYS_GUID();

-- USER_DEVICES
ALTER TABLE USER_DEVICES DROP PRIMARY KEY;
ALTER TABLE USER_DEVICES DROP COLUMN USER_ID;
ALTER TABLE USER_DEVICES RENAME COLUMN NEW_USER_ID TO USER_ID;
ALTER TABLE USER_DEVICES ADD CONSTRAINT PK_USER_DEVICES PRIMARY KEY (USER_ID, DEVICE_ID);

-- FUEL 
ALTER TABLE FUEL DROP PRIMARY KEY;
ALTER TABLE FUEL DROP COLUMN ID;
ALTER TABLE FUEL DROP COLUMN USER_ID;
ALTER TABLE FUEL DROP COLUMN CAR_ID;
ALTER TABLE FUEL RENAME COLUMN NEW_ID TO ID;
ALTER TABLE FUEL RENAME COLUMN NEW_USER_ID TO USER_ID;
ALTER TABLE FUEL RENAME COLUMN NEW_CAR_ID TO CAR_ID;
ALTER TABLE FUEL ADD CONSTRAINT PK_FUEL PRIMARY KEY (ID);
ALTER TABLE FUEL MODIFY ID DEFAULT SYS_GUID();
ALTER TABLE FUEL MODIFY USER_ID DEFAULT NULL NOT NULL;
ALTER TABLE FUEL MODIFY CAR_ID DEFAULT NULL NOT NULL;

-- BLUETOOTH
ALTER TABLE BLUETOOTH DROP PRIMARY KEY;
ALTER TABLE BLUETOOTH DROP COLUMN ID;
ALTER TABLE BLUETOOTH DROP COLUMN USER_ID;
ALTER TABLE BLUETOOTH DROP COLUMN CAR_ID;
ALTER TABLE BLUETOOTH RENAME COLUMN NEW_ID TO ID;
ALTER TABLE BLUETOOTH RENAME COLUMN NEW_USER_ID TO USER_ID;
ALTER TABLE BLUETOOTH RENAME COLUMN NEW_CAR_ID TO CAR_ID;
ALTER TABLE BLUETOOTH ADD CONSTRAINT PK_BLUETOOTH PRIMARY KEY (ID);
ALTER TABLE BLUETOOTH MODIFY ID DEFAULT SYS_GUID();
ALTER TABLE BLUETOOTH MODIFY USER_ID DEFAULT NULL NOT NULL;

-- SESSION_DATA
-- (Only the reference to CARs changed for sessions)
ALTER TABLE SESSION_DATA DROP COLUMN CAR_ID;
ALTER TABLE SESSION_DATA RENAME COLUMN NEW_CAR_ID TO CAR_ID;

-- 6. Add Sync Columns (offline capabilities) to ALL tables
-- We check all tables that could realistically be synchronized
ALTER TABLE USERS ADD UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE USERS ADD IS_DELETED NUMBER DEFAULT 0;

ALTER TABLE CARS ADD UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE CARS ADD IS_DELETED NUMBER DEFAULT 0;

ALTER TABLE FUEL ADD UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE FUEL ADD IS_DELETED NUMBER DEFAULT 0;

ALTER TABLE BLUETOOTH ADD UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE BLUETOOTH ADD IS_DELETED NUMBER DEFAULT 0;

ALTER TABLE API_KEYS ADD UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE API_KEYS ADD IS_DELETED NUMBER DEFAULT 0;

ALTER TABLE DEVICES ADD UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE DEVICES ADD IS_DELETED NUMBER DEFAULT 0;

ALTER TABLE LOCATION ADD UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE LOCATION ADD IS_DELETED NUMBER DEFAULT 0;

ALTER TABLE LOCATION_DATA ADD UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE LOCATION_DATA ADD IS_DELETED NUMBER DEFAULT 0;

ALTER TABLE LOCATION_GEOCODE ADD UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE LOCATION_GEOCODE ADD IS_DELETED NUMBER DEFAULT 0;

ALTER TABLE PARAMETER ADD UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE PARAMETER ADD IS_DELETED NUMBER DEFAULT 0;

ALTER TABLE SESSION_DATA ADD UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE SESSION_DATA ADD IS_DELETED NUMBER DEFAULT 0;

ALTER TABLE USER_DEVICES ADD UPDATED_AT TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE USER_DEVICES ADD IS_DELETED NUMBER DEFAULT 0;

-- 7. Restore Foreign Key constraints
ALTER TABLE API_KEYS ADD CONSTRAINT FK_API_KEYS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;
ALTER TABLE USER_DEVICES ADD CONSTRAINT FK_USER_DEVICES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;
ALTER TABLE CARS ADD CONSTRAINT FK_CARS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;
ALTER TABLE SESSION_DATA ADD CONSTRAINT FK_SESSION_CAR FOREIGN KEY (CAR_ID) REFERENCES CARS(ID) ON DELETE SET NULL;
ALTER TABLE FUEL ADD CONSTRAINT FK_FUEL_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;
ALTER TABLE FUEL ADD CONSTRAINT FK_FUEL_CAR FOREIGN KEY (CAR_ID) REFERENCES CARS(ID) ON DELETE CASCADE;
ALTER TABLE BLUETOOTH ADD CONSTRAINT FK_BLUETOOTH_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE;
ALTER TABLE BLUETOOTH ADD CONSTRAINT FK_BLUETOOTH_CAR FOREIGN KEY (CAR_ID) REFERENCES CARS(ID) ON DELETE SET NULL;

-- 8. Final Commit
COMMIT;
