-- Migration script to update default values for CREATED_AT and UPDATED_AT to UTC

-- API_KEYS
ALTER TABLE API_KEYS MODIFY CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE API_KEYS MODIFY UPDATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);

-- BLUETOOTH
ALTER TABLE BLUETOOTH MODIFY CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE BLUETOOTH MODIFY UPDATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);

-- CARS
ALTER TABLE CARS MODIFY CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE CARS MODIFY UPDATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);

-- DEVICES
ALTER TABLE DEVICES MODIFY CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE DEVICES MODIFY UPDATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);

-- FUEL
ALTER TABLE FUEL MODIFY CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE FUEL MODIFY UPDATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);

-- LOCATION
ALTER TABLE LOCATION MODIFY CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE LOCATION MODIFY UPDATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);

-- LOCATION_DATA
ALTER TABLE LOCATION_DATA MODIFY CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE LOCATION_DATA MODIFY UPDATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);

-- LOCATION_GEOCODE
ALTER TABLE LOCATION_GEOCODE MODIFY CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE LOCATION_GEOCODE MODIFY UPDATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);

-- PARAMETER
ALTER TABLE PARAMETER MODIFY CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE PARAMETER MODIFY UPDATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);

-- SESSION_DATA
ALTER TABLE SESSION_DATA MODIFY CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE SESSION_DATA MODIFY UPDATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);

-- SYNC_STATE (only has UPDATED_AT)
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SYNC_STATE MODIFY UPDATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN -- Ignore if table doesn't exist
            RAISE;
        END IF;
END;
/

-- USERS
ALTER TABLE USERS MODIFY CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE USERS MODIFY UPDATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);

-- USER_DEVICES
ALTER TABLE USER_DEVICES MODIFY CREATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
ALTER TABLE USER_DEVICES MODIFY UPDATED_AT DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP);
